<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Marcus Ramirez" />

<meta name="date" content="2021-11-01" />

<title>Exam 2</title>

<script src="site_libs/header-attrs-2.10/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Marcus' Site</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Assignments.html">Assignments</a>
</li>
<li>
  <a href="Assignment1.html">Assignment 1</a>
</li>
<li>
  <a href="Assignment2.html">Assignment 2</a>
</li>
<li>
  <a href="Assignment3.html">Assignment 3</a>
</li>
<li>
  <a href="Assignment4.html">Assignment 4</a>
</li>
<li>
  <a href="Exam1.html">Exam 1</a>
</li>
<li>
  <a href="Exam2.html">Exam 2</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Exam 2</h1>
<h4 class="author">Marcus Ramirez</h4>
<h4 class="date">11/01/2021</h4>

</div>


<div id="instructions" class="section level1">
<h1>Instructions</h1>
<ol style="list-style-type: lower-alpha">
<li><p>Create a folder in your computer (a good place would be under Crim 250, Exams).</p></li>
<li><p>Download the dataset from the Canvas website (sim.data.csv) onto that folder, and save your Exam 2.Rmd file in the same folder.</p></li>
<li><p>Data description: This dataset provides (simulated) data about 200 police departments in one year. It contains information about the funding received by the department as well as incidents of police brutality. Suppose this dataset (sim.data.csv) was collected by researchers to answer this question: <strong>“Does having more funding in a police department lead to fewer incidents of police brutality?”</strong></p></li>
<li><p>Codebook:</p></li>
</ol>
<ul>
<li>funds: How much funding the police department received in that year in millions of dollars.</li>
<li>po.brut: How many incidents of police brutality were reported by the department that year.</li>
<li>po.dept.code: Police department code</li>
</ul>
</div>
<div id="problem-1-eda-10-points" class="section level1">
<h1>Problem 1: EDA (10 points)</h1>
<p>Describe the dataset and variables. Perform exploratory data analysis for the two variables of interest: funds and po.brut.</p>
<pre class="r"><code>dat5 &lt;- read.csv(file = &#39;sim.data.csv&#39;)
hist(dat5$funds, main=&quot;Histogram of Police Funding&quot;, xlab=&quot;Funding (in millions of dollars)&quot;, ylab=&quot;Frequency&quot;)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<pre class="r"><code>hist(dat5$po.brut, main=&quot;Histogram of Police Brutality&quot;, xlab=&quot;Incidents of Police Brutality&quot;, ylab=&quot;Frequency&quot;)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
<pre class="r"><code>table(dat5$funds)</code></pre>
<pre><code>## 
## 21.4 27.9 29.1 30.7   31 31.2 34.2 34.4 34.5   36 37.4 39.1 39.5 40.2 40.4 40.9 
##    1    1    1    2    1    1    1    1    1    1    1    2    1    1    1    1 
## 41.6 41.7 41.8 42.1 42.2 43.2 43.6 44.5 44.6 44.7 45.5 46.4 46.8 47.4 47.9 48.1 
##    1    1    1    1    1    1    1    1    3    1    1    1    1    1    1    1 
## 48.6 48.7 49.3 49.4 49.8   50 50.4 50.8 50.9 51.1 51.5 51.6 51.7 51.8   52 52.2 
##    1    2    1    1    1    1    1    2    1    1    1    1    1    2    1    1 
## 52.6 52.9   53 53.4 53.6 53.8   54 54.4 54.7 54.8 54.9 55.5 55.6 56.1 56.2 56.3 
##    1    2    2    1    2    2    1    1    1    1    1    1    2    1    1    1 
## 56.4 56.5 56.8 57.2 57.3 57.6 57.8 57.9 58.3 58.5 58.6 58.9   59 59.1 59.5 59.6 
##    1    2    1    2    1    2    1    2    2    1    1    1    2    1    1    2 
## 59.7 59.8 60.1 60.2 60.3 60.4 61.2 61.5 61.7 61.9 62.1 62.2 62.5 62.8 63.5 63.8 
##    1    2    2    1    1    1    1    1    1    1    1    1    1    3    3    1 
## 64.2 64.3   65 65.2 65.4 65.7 65.9 66.2 66.4 66.9 67.4 67.5 67.6 68.1 68.2   69 
##    1    1    2    1    1    1    1    1    1    1    1    1    1    1    1    1 
## 69.1 70.4 70.7 70.8 71.3 71.6 71.7 71.8 71.9   72 72.7 72.8 72.9   73 73.5   74 
##    1    1    1    2    1    1    1    1    1    2    1    1    1    1    1    1 
## 74.1 74.2 74.4 74.6 74.8 74.9   75 75.3 75.5   76 76.6 77.3 77.7 78.2 78.6 78.9 
##    1    2    1    1    1    1    2    3    1    1    1    1    1    1    1    1 
## 79.1 79.3 79.9 80.8 80.9 81.4   82 82.6 82.7 82.9 83.2 83.9 84.3   85 85.1 86.4 
##    1    2    1    1    1    1    1    1    1    1    1    1    1    1    1    1 
## 89.1 93.4 93.9 94.4 96.5 99.7 
##    1    2    1    1    1    1</code></pre>
<p><strong>The funds variable is a quantitative variable and so is the incidents of police brutality since both variables are measured with numerical values. Thus,I opted for a univariate graphical representation in the form of a histogram that could show frequency distributions of both variables. From the funds histogram, I can see that the most frequent funding amount is between 50 and 60 million dollars. The histogram for police brutality incidents indicates that the data is skewed left with a generally positive trend towards more incidents of police brutality.</strong></p>
</div>
<div id="problem-2-linear-regression-30-points" class="section level1">
<h1>Problem 2: Linear regression (30 points)</h1>
<ol style="list-style-type: lower-alpha">
<li>Perform a simple linear regression to answer the question of interest. To do this, name your linear model “reg.output” and write the summary of the regression by using “summary(reg.output)”.</li>
</ol>
<pre class="r"><code># Remember to remove eval=FALSE!!
reg.output &lt;- lm(formula = funds ~ po.brut, data = dat5)
summary(reg.output)</code></pre>
<pre><code>## 
## Call:
## lm(formula = funds ~ po.brut, data = dat5)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.8979  -0.7889   0.7154   1.4973   3.1473 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 109.0168     0.6145  177.41   &lt;2e-16 ***
## po.brut      -2.6455     0.0324  -81.64   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.541 on 198 degrees of freedom
## Multiple R-squared:  0.9712, Adjusted R-squared:  0.971 
## F-statistic:  6666 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Your answer here.</strong></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Report the estimated coefficient, standard error, and p-value of the slope. Is the relationship between funds and incidents statistically significant? Explain.</li>
</ol>
<p><strong>The estimated coefficient is -2.6455, the standard error is 0.0324, and the p-value is &lt;2e-16. The relationship between funds and incidents is statiscally significant because the estimated p-value (&lt;2e-16) is less than the chosen significance level of 0.5. This indicates that we can reject the null hypothesis. It also means that if the null hypothesis were to be true and there was no relationship between funds and incidents, we could except to observe a t-statstic as extreme as the one we observed with a &lt;2e-16 probability. </strong></p>
<ol start="3" style="list-style-type: lower-alpha">
<li>Draw a scatterplot of po.brut (y-axis) and funds (x-axis). Right below your plot command, use abline to draw the fitted regression line, like this:</li>
</ol>
<pre class="r"><code># Remember to remove eval=FALSE!!
plot(dat5$funds, dat5$po.brut,  main=&quot;Relationship between Funding and Police Brutality Incidents&quot;,
    xlab=&quot;Funding (in millions per year)&quot;, ylab=&quot;Police Brutality (# of incidents)&quot;)
abline(reg.output, col = &quot;red&quot;, lwd=2)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-3-1.png" width="384" /> Does the line look like a good fit? Why or why not?</p>
<p><strong>The line does not look like a good fit because the majority of the data coordinates on the scatterplot are not found along the line. Thus, it does not accurately reflect the data on the scatterplot and isn’t exactly a line of best fit.</strong></p>
<ol start="4" style="list-style-type: lower-alpha">
<li>Are the four assumptions of linear regression satisfied? To answer this, draw the relevant plots. (Write a maximum of one sentence per assumption.) If not, what might you try to do to improve this (if you had more time)?</li>
</ol>
<pre class="r"><code>plot(dat5$funds, reg.output$residuals, ylim=c(-15,15), main=&quot;Residuals vs. x&quot;, xlab=&quot;x, Funds&quot;, ylab=&quot;Residuals&quot;)
abline(h = 0, lty=&quot;dashed&quot;)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>plot(reg.output, which=1)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre class="r"><code>plot(reg.output, which=3)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<pre class="r"><code>plot(reg.output, which=5)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<pre class="r"><code>plot(reg.output, which=2)</code></pre>
<p><img src="Exam2_files/figure-html/unnamed-chunk-4-5.png" width="672" /></p>
<p><strong>The linearity assumption is not satisfied because when I plot the residuals against x or against the predicted values there is a pattern or general shape formed by the plot rather than appearing entirely random; the red line on the Residuals vs. Fitted plot is arched rather than flat.The independence assumption is not satisfied because when we plot the residuals against x there is evidence of patterns or clumping of data (suggests failure of independence). The equal variance (homoscedasticity) assumption is not satisfied because when looking at the scale-location plot, the red line is not flat which indicates that the errors may not have constant variance (there seems to be a trend in the red line that it’s following). The normal population assumption is not satisfied because the residuals look far from normal. Also, it’s worth noting that the qq plot appears left skewed which contributes to it not matching what we would expect from a normal distribution. To improve this, if I had more time I might transform the data by using mathematical operations to change its measurement scale. This would help us fit a model better and work towards achieving better linearity. </strong></p>
<ol start="5" style="list-style-type: lower-alpha">
<li>Answer the question of interest based on your analysis.</li>
</ol>
<p><strong>While we cannot argue that increasing funding causes police brutality incidents to decrease, we can make correlational claims about their relationship. So, in short, no we cannot say that increasing funds in a police department leads to lower incidents of police brutality. This is because correlation doesn’t necessarily indicate causation. In this case it would be less practical to say “if you increase funding by one unit, police brutality incidents will decrease by 2.6455,” rather one should say “for a higher funding, by one unit, reported police brutality incidents were lower by 2.6455, on average.” In this way we make a claim about the strength of their relationship and provide commentary on the predictions we can draw. </strong></p>
</div>
<div id="problem-3-data-ethics-10-points" class="section level1">
<h1>Problem 3: Data ethics (10 points)</h1>
<p>Describe the dataset. Considering our lecture on data ethics, what concerns do you have about the dataset? Once you perform your analysis to answer the question of interest using this dataset, what concerns might you have about the results?</p>
<p><strong>I may be concerned about how the data for police brutality incidents was gathered in this dataset. If police departments self-reported these numbers, it could be the case that they underreported incidents of police brutality with the awareness that substantially higher rates may lead to feelings of distrust within the communities they patrol. In the lecture, we discussed how police databases aren’t a compelte census of all criminal offenses and don’t necessarily guarantee a representative random sample. Thus, some of the options from the “data ethics checklist” are worth considering such as checking for possible sources fo bias and testing data to ensure it’s representative. Especially since police department codes are provided to match the incident rates to which department they come from and may influence public perceptions of police safety. </strong></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
